language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      env:
      - BUILD_TARGET=gcc_build
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      env:
        - BUILD_TARGET=gcc_build
        - CC=gcc-5
        - CXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      env:
        - BUILD_TARGET=gcc_build
        - CC=gcc-6
        - CXX=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
    - os: linux
      sudo: required
      services:
        - docker
      env: BUILD_TARGET=docker_build
    - os: osx
      osx_image: xcode8
      env:
        - BUILD_TARGET=osx_build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

install:
- set -e
- if [[ "${BUILD_TARGET}" = "docker_build" ]]; then
    pip install --user awscli;
    $(aws ecr get-login --region eu-central-1);
    docker pull ${DOCKER_REPO};
  fi

script:
- if [[ "${BUILD_TARGET}" = "gcc_build" ]]; then
    make;
    make run_unit_tests;
  fi
- if [[ "${BUILD_TARGET}" = "docker_build" ]]; then
    docker run -it -v $TRAVIS_BUILD_DIR:/home/docker1000/src/DroneLink:rw ${DOCKER_REPO} make;
    docker run -it -v $TRAVIS_BUILD_DIR:/home/docker1000/src/DroneLink:rw ${DOCKER_REPO} make run_unit_tests;
    docker run -it -v $TRAVIS_BUILD_DIR:/home/docker1000/src/DroneLink:rw ${DOCKER_REPO} make fix_style;
  fi
- if [[ "${BUILD_TARGET}" = "osx_build" ]]; then
    make;
    make run_unit_tests;
  fi
