# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - x64

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug

# scripts that are called at very beginning, before repo cloning
init:
  - cmake --version
  - msbuild /version

# clone directory
clone_folder: C:\dronecore

# scripts to run before build
before_build:
  - cd C:\dronecore
  - git submodule update --init --recursive --depth 20
  - cd C:\
  - appveyor DownloadFile https://curl.haxx.se/download/curl-7.55.1.zip
  - 7z x -y curl-7.55.1.zip

build: on

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd curl-7.55.1\winbuild
  - nmake /f Makefile.vc mode=static VC=14 MACHINE=x64 DEBUG=no
  - cd C:\dronecore
  - md build
  - cd build
  - cmake -DWIN_CURL_INCLUDE_DIR:STRING=C:\\curl-7.55.1\\include -DWIN_CURL_LIB:STRING="C:\curl-7.55.1\builds\libcurl-vc14-x64-release-static-ipv6-sspi-winssl\lib\libcurl_a.lib" -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --target install

test: on

test_script:
  - cd C:\dronecore
  - build\Debug\unit_tests_runner.exe
